var MERCH = [
  // ── In Stock ──
  {
    title: "MNNM BLCK Leather Crossbody Bag",
    artist: "",
    type: "Bag",
    price: "€120",
    soldOut: false,
    catalog: "",
    url: "https://monnomblack.bandcamp.com/merch/mnnm-blck-leather-crossbody-bag",
    img: "https://f4.bcbits.com/img/0042068286_10.jpg",
    desc: "Hand made in Italy, 100% full grain leather, Monnom Black Crossbody Bag. Features a sleek metal logo plaque on the front. Inside, you'll find dedicated card slots and an internal slip pocket for your phone, keeping essentials organized and easily accessible. Adjustable strap and buckle in matching leather ensures a customized fit, whether it's across the body, around the waist, or slung over the shoulder. Limited edition."
  },
  {
    title: "Quantum Leap EP",
    artist: "LPV",
    type: "Double Vinyl LP",
    price: "€24",
    soldOut: false,
    catalog: "MONNOM039",
    url: "https://monnomblack.bandcamp.com/album/quantum-leap-ep",
    img: "https://f4.bcbits.com/img/0040097354_10.jpg",
    desc: "LPV makes a striking debut on Monnom Black with an expansive double EP, delivering eight meticulously crafted tracks that fuse dub, bleep, and bass into peak-time weapons. Double vinyl + Monnom Black sticker + shrink wrap + A5 insert."
  },
  {
    title: "Mechanized EP",
    artist: "Lars Huismann",
    type: "Double Vinyl LP",
    price: "€24",
    soldOut: false,
    catalog: "MONNOM037",
    url: "https://monnomblack.bandcamp.com/album/mechanized-ep",
    img: "https://f4.bcbits.com/img/0038057218_10.jpg",
    desc: "Berlin-based techno producer Lars Huismann makes his debut on Monnom Black with eight tracks crafted with meticulous precision, blending hypnotic melodies and intense dubbed-out grooves. Double vinyl + Monnom Black sticker + shrink wrap."
  },
  {
    title: "War Is Peace, Freedom is Slavery, Ignorance is Strength",
    artist: "Dax J",
    type: "Double Vinyl LP",
    price: "€24",
    soldOut: false,
    catalog: "MONNOM036",
    url: "https://monnomblack.bandcamp.com/album/war-is-peace-freedom-is-slavery-ignorance-is-strength",
    img: "https://f4.bcbits.com/img/0037320736_10.jpg",
    desc: "Referencing the political slogans in Orwell's dystopian novel 1984, where language is manipulated to control and oppress, we find a stark reflection in modern society, where truth is frequently distorted, and freedoms are increasingly compromised — echoing the very tactics Orwell warned against."
  },
  {
    title: "The World Of Monnom Black III",
    artist: "Various Artists",
    type: "Triple 12\" Vinyl EP",
    price: "€35",
    soldOut: false,
    catalog: "MONNOM035",
    url: "https://monnomblack.bandcamp.com/album/the-world-of-monnom-black-iii",
    img: "https://f4.bcbits.com/img/0033722360_10.jpg",
    desc: "The World of Monnom Black makes its triumphant return, unveiling the highly anticipated third iteration of its iconic release and ushering in a wealth of new artistic voices into its ever-expanding universe. Celebrated for curating the finest handpicked music, the series remains a beacon for championing the true essence of techno. Presented on triple vinyl and graced by 19 esteemed artists, marking this as the label's most innovative and important release to date."
  },
  {
    title: "The World Of Monnom Black II",
    artist: "Various Artists",
    type: "Triple 12\" Vinyl EP",
    price: "€35",
    soldOut: false,
    catalog: "MONNOM020",
    url: "https://monnomblack.bandcamp.com/album/the-world-of-monnom-black-ii",
    img: "https://f4.bcbits.com/img/0018047019_10.jpg",
    desc: "To celebrate its landmark 20th release, Monnom Black invites you to enter The World of Monnom Black II — a return trip to techno's most uncompromising landscape. The triple vinyl release features 14 hand-picked contributions from the label's trusted collaborators alongside cutting-edge artists new to the roster."
  },
  {
    title: "Beyond The Visible Spectrum EP",
    artist: "UMWELT",
    type: "12\" Vinyl",
    price: "€12",
    soldOut: false,
    catalog: "MONNOM038",
    url: "https://monnomblack.bandcamp.com/album/beyond-the-visible-spectrum-ep",
    img: "https://f4.bcbits.com/img/0038769059_10.jpg",
    desc: "Umwelt unveils his latest EP, featuring six tracks that highlight his unique analog style. Fusing techno, electro, and machine-driven rhythms, crafting his signature sonic landscapes that define the Umwelt sound."
  },
  {
    title: "MNNM BLCK Premium Canvas Wide Gusset Tote Bag",
    artist: "",
    type: "Bag",
    price: "€22",
    soldOut: false,
    catalog: "",
    url: "https://monnomblack.bandcamp.com/merch/mnnm-blck-premium-canvas-wide-gusset-tote-bag",
    img: "https://f4.bcbits.com/img/0037551460_10.jpg",
    desc: "Premium heavy duty canvas tote bag with extra large gusset. Screen printed on both sides. Made of durable cotton canvas, the 13cm all round gusset gives this large canvas tote bag extra capacity so the bag can hold up to 40 records. 100% heavy cotton canvas, 407 g/m², 390mm x 420mm x 130mm. Long Handles: 570mm. Capacity 19 litres."
  },
  {
    title: "Utopian Surrealism LP",
    artist: "Dax J",
    type: "Double Vinyl LP",
    price: "€16",
    soldOut: false,
    catalog: "MONNOM026",
    url: "https://monnomblack.bandcamp.com/album/utopian-surrealism-lp",
    img: "https://f4.bcbits.com/img/0026406115_10.jpg",
    desc: "Dax J's Utopian Surrealism observes our transition into a new dystopian era. It reflects the strain in distinguishing truth and reality from the ever-growing radicalised networks of global manipulation, whilst extreme polarised realities, AI, deception, and mass poverty stay hidden away as we accelerate into the next stage of evolution. Written during lockdown, inspired by Yuval Noah Harari's book Sapiens."
  },
  {
    title: "Petra 02 (Dax J Remix) EP",
    artist: "Christopher Just",
    type: "12\" Vinyl",
    price: "€8",
    soldOut: false,
    catalog: "MONNOM032",
    url: "https://monnomblack.bandcamp.com/album/petra-02-dax-j-remix-ep",
    img: "https://f4.bcbits.com/img/0031943801_10.jpg",
    desc: "Electronic pioneer Christopher Just's initial music came out in 1993 under his own name and various pseudonyms, like 'DJ One Finger' and 'Ilsa Gold'. The 'Petra' project was originally released in 1996 showcasing the ferocious sound of 90's analog hardware."
  },
  {
    title: "The Invisible Man EP",
    artist: "Dax J",
    type: "12\" Vinyl",
    price: "€12",
    soldOut: false,
    catalog: "MONNOM009",
    url: "https://monnomblack.bandcamp.com/album/the-invisible-man-ep",
    img: "https://f4.bcbits.com/img/0018028828_10.jpg",
    desc: "Pressed on high quality 140gm black 12\" vinyl comes with additional insert & sticker."
  },
  {
    title: "M. Bison EP",
    artist: "Vanquished",
    type: "12\" Vinyl",
    price: "€8",
    soldOut: false,
    catalog: "VANQUISHED111",
    url: "https://monnomblack.bandcamp.com/album/m-bison-ep",
    img: "https://f4.bcbits.com/img/0038880396_10.jpg",
    desc: "An unknown artist by the name of Vanquished releases techno inspired by Street Fighter characters."
  },
  {
    title: "Organic Computer Awareness",
    artist: "LDS",
    type: "12\" Vinyl",
    price: "€12",
    soldOut: false,
    catalog: "MONNOM023",
    url: "https://monnomblack.bandcamp.com/album/organic-computer-awareness",
    img: "https://f4.bcbits.com/img/0022263958_10.jpg",
    desc: "Known for his futuristic, dub techno sound, Stuttgart's LDS releases his 1st full EP on Monnom Black to shine some light during these cold isolated times."
  },
  {
    title: "Shades Of Black LP",
    artist: "Dax J",
    type: "Double Vinyl LP",
    price: "€16",
    soldOut: false,
    catalog: "MONNOM007",
    url: "https://monnomblack.bandcamp.com/album/shades-of-black-lp",
    img: "https://f4.bcbits.com/img/0018161168_10.jpg",
    desc: "Dax J's 1st solo full length Techno album Shades of Black. Drawing inspiration from Acid, Jungle, Drum n Bass & UK Rave, combining a diverse fusion of tempos, moods and breakbeats."
  },
  {
    title: "King Of The Sewers EP",
    artist: "Dax J & UVB",
    type: "12\" Vinyl",
    price: "€10",
    soldOut: false,
    catalog: "MONNOM019",
    url: "https://monnomblack.bandcamp.com/album/king-of-the-sewers-ep",
    img: "https://f4.bcbits.com/img/0017976343_10.jpg",
    desc: "Four cuts of pulsating techno from two of electronic music's most uncompromising young figures. A gritty soundtrack inspired by forgotten lives beneath eastern-bloc cities."
  },
  {
    title: "Chaos Come To Conquer EP",
    artist: "Dax J",
    type: "12\" Vinyl",
    price: "€12",
    soldOut: false,
    catalog: "MONNOM018",
    url: "https://monnomblack.bandcamp.com/album/chaos-come-to-conquer-ep",
    img: "https://f4.bcbits.com/img/0016130657_10.jpg",
    desc: "Dax J returns to Monnom Black with an ep of uncompromising warehouse tracks, drifting through acid, UK & jungle influences to create an iconic onslaught of ominous Techno cuts."
  },
  {
    title: "Redemption EP",
    artist: "Dax J",
    type: "Double 12\" Vinyl",
    price: "€16",
    soldOut: false,
    catalog: "MONNOM015",
    url: "https://monnomblack.bandcamp.com/album/redemption-ep",
    img: "https://f4.bcbits.com/img/0018161311_10.jpg",
    desc: "Dax J returns to Monnom Black with a double EP of Techno and Acid weapons! Double vinyl + A5 photo card insert + free download codes + Monnom Black sticker + protective plastic sleeve."
  },
  {
    title: "Offending Public Morality LP",
    artist: "Dax J",
    type: "Double Vinyl LP",
    price: "€16",
    soldOut: false,
    catalog: "MONNOM014",
    url: "https://monnomblack.bandcamp.com/album/offending-public-morality-lp",
    img: "https://f4.bcbits.com/img/0018028530_10.jpg",
    desc: "Dax J's success within the challenging environment of international DJing and music production has been considerable. He has used his recent experiences to create sonic weapons to confront public morality. Touching upon numerous hot button issues, Offending Public Morality sprawls out like a foreboding urban landscape."
  },
  {
    title: "Offending Public Morality LP — Limited Edition CD",
    artist: "Dax J",
    type: "Compact Disc",
    price: "€4",
    soldOut: false,
    catalog: "MONNOM014CD",
    url: "https://monnomblack.bandcamp.com/album/offending-public-morality-lp",
    img: "https://f4.bcbits.com/img/0013002042_10.jpg",
    desc: "Limited Edition Compact Disc of Dax J's second album Offending Public Morality."
  },
  {
    title: "Utopian Surrealism Album Sampler",
    artist: "Dax J",
    type: "12\" Vinyl",
    price: "€7",
    soldOut: false,
    catalog: "MONNOM025",
    url: "https://monnomblack.bandcamp.com/album/utopian-surrealism-album-sampler",
    img: "https://f4.bcbits.com/img/0025111050_10.jpg",
    desc: "Album sampler for Dax J's 3rd studio album Utopian Surrealism, exploring our transition into a new dystopian era."
  },
  {
    title: "State Of Control EP",
    artist: "I Hate Models",
    type: "12\" Vinyl",
    price: "€12",
    soldOut: false,
    catalog: "MONNOM011",
    url: "https://monnomblack.bandcamp.com/album/state-of-control-ep",
    img: "https://f4.bcbits.com/img/0018161276_10.jpg",
    desc: "I Hate Models makes his debut on Monnom Black bringing his trademark sound and style, anthemic ebm, acid, rave, techno killers."
  },
  {
    title: "Highest Sense EP",
    artist: "Stranger",
    type: "12\" Vinyl",
    price: "€12",
    soldOut: false,
    catalog: "MONNOM008",
    url: "https://monnomblack.bandcamp.com/album/highest-sense-ep",
    img: "https://f4.bcbits.com/img/0018028897_10.jpg",
    desc: "Monnom Black 008 comes from Stranger, one of Rotterdam's fast rising talents. Known for his love of classic Techno, Stranger delivers 4 peak-time Rave Acidic cuts, ready to do the damage."
  },
  {
    title: "Basement EP",
    artist: "Kaelan",
    type: "12\" Vinyl",
    price: "€10",
    soldOut: false,
    catalog: "MONNOM002",
    url: "https://monnomblack.bandcamp.com/album/basement-ep",
    img: "https://f4.bcbits.com/img/0018028234_10.jpg",
    desc: "Pressed on high quality 140gm black 12\" vinyl comes with additional sticker."
  },
  {
    title: "Infinite Abyss EP",
    artist: "Dax J",
    type: "12\" Marbled Vinyl",
    price: "€10",
    soldOut: false,
    catalog: "MONNOM003",
    url: "https://monnomblack.bandcamp.com/album/infinite-abyss-ep",
    img: "https://f4.bcbits.com/img/0018046740_10.jpg",
    desc: "The 3rd Release from Monnom Black sees 4 new original tracks from Dax J. Acidic, rave dance-floor weapons."
  },
  {
    title: "Body Music Album Teaser",
    artist: "Thomas P. Heckmann",
    type: "12\" Vinyl",
    price: "€6",
    soldOut: false,
    catalog: "MONNOM012",
    url: "https://monnomblack.bandcamp.com/album/body-music-album-teaser",
    img: "https://f4.bcbits.com/img/0018028919_10.jpg",
    desc: "Thomas P. Heckmann has flexed his prowess across all shades of electronic music, but it's his contributions to EBM-techno, acid, industrial, and experimental that has earned him his notoriety. This 3 track teaser gives you a taste of what is to come."
  },
  {
    title: "Shades Of Black LP — Limited Edition CD",
    artist: "Dax J",
    type: "Compact Disc",
    price: "€5",
    soldOut: false,
    catalog: "MONNOM007CD",
    url: "https://monnomblack.bandcamp.com/album/shades-of-black-lp",
    img: "https://f4.bcbits.com/img/0029094843_10.jpg",
    desc: "Limited Edition Compact Disc of Dax J's debut album Shades Of Black."
  },
  {
    title: "Body Music LP — Limited Edition CD",
    artist: "Thomas P. Heckmann",
    type: "Compact Disc",
    price: "€4",
    soldOut: false,
    catalog: "MONNOM013CD",
    url: "https://monnomblack.bandcamp.com/album/body-music-lp",
    img: "https://f4.bcbits.com/img/0025141330_10.jpg",
    desc: "Limited Edition Compact Disc of Thomas P. Heckmann's Body Music LP."
  },
  // ── Sold Out ──
  {
    title: "Generation Lost EP",
    artist: "Ryuji Takeuchi",
    type: "12\" Vinyl",
    price: "Sold Out",
    soldOut: true,
    catalog: "MONNOM031",
    url: "https://monnomblack.bandcamp.com/album/generation-lost-ep",
    img: "https://f4.bcbits.com/img/0031798609_10.jpg",
    desc: ""
  },
  {
    title: "Brixton EP",
    artist: "Dax J",
    type: "12\" Vinyl",
    price: "Sold Out",
    soldOut: true,
    catalog: "MONNOM030",
    url: "https://monnomblack.bandcamp.com/album/brixton-ep",
    img: "https://f4.bcbits.com/img/0031145393_10.jpg",
    desc: ""
  },
  {
    title: "Mispress EP",
    artist: "Binny",
    type: "12\" Vinyl",
    price: "Sold Out",
    soldOut: true,
    catalog: "MONNOM006",
    url: "https://monnomblack.bandcamp.com/album/mispress-ep",
    img: "https://f4.bcbits.com/img/0017974406_10.jpg",
    desc: ""
  },
  {
    title: "Dreamscape EP",
    artist: "Dax J",
    type: "12\" Vinyl",
    price: "Sold Out",
    soldOut: true,
    catalog: "MONNOM001",
    url: "https://monnomblack.bandcamp.com/album/dreamscape-ep",
    img: "https://f4.bcbits.com/img/0018047381_10.jpg",
    desc: ""
  },
  {
    title: "LSD EP",
    artist: "Remco Beekwilder",
    type: "12\" Vinyl",
    price: "Sold Out",
    soldOut: true,
    catalog: "MONNOM010",
    url: "https://monnomblack.bandcamp.com/album/lsd-ep",
    img: "https://f4.bcbits.com/img/0018029246_10.jpg",
    desc: ""
  },
  {
    title: "Daytona EP",
    artist: "Fractions",
    type: "12\" Vinyl",
    price: "Sold Out",
    soldOut: true,
    catalog: "MONNOM027",
    url: "https://monnomblack.bandcamp.com/album/daytona-ep",
    img: "https://f4.bcbits.com/img/a2044820003_10.jpg",
    desc: ""
  },
  {
    title: "End Of Opulence",
    artist: "Dax J",
    type: "12\" Vinyl",
    price: "Sold Out",
    soldOut: true,
    catalog: "MONNOM022",
    url: "https://monnomblack.bandcamp.com/album/end-of-opulence",
    img: "https://f4.bcbits.com/img/a3827754670_10.jpg",
    desc: ""
  },
  {
    title: "Unholy Empire",
    artist: "Aahan",
    type: "12\" Vinyl",
    price: "Sold Out",
    soldOut: true,
    catalog: "MONNOM024",
    url: "https://monnomblack.bandcamp.com/album/unholy-empire",
    img: "https://f4.bcbits.com/img/a0764710998_10.jpg",
    desc: ""
  },
  {
    title: "Imperial Propaganda EP",
    artist: "Dax J",
    type: "12\" Vinyl",
    price: "Sold Out",
    soldOut: true,
    catalog: "MONNOM005",
    url: "https://monnomblack.bandcamp.com/album/imperial-propaganda-ep",
    img: "https://f4.bcbits.com/img/a2044281629_10.jpg",
    desc: ""
  },
  {
    title: "NITE NRG",
    artist: "Fractions",
    type: "12\" Vinyl",
    price: "Sold Out",
    soldOut: true,
    catalog: "MONNOM021",
    url: "https://monnomblack.bandcamp.com/album/nite-nrg",
    img: "https://f4.bcbits.com/img/a3773839850_10.jpg",
    desc: ""
  },
  {
    title: "Legacy LP",
    artist: "Thomas P. Heckmann",
    type: "Triple 12\" Vinyl LP",
    price: "Sold Out",
    soldOut: true,
    catalog: "MONNOM034",
    url: "https://monnomblack.bandcamp.com/album/legacy-lp",
    img: "https://f4.bcbits.com/img/a2118571898_10.jpg",
    desc: ""
  },
  {
    title: "Vyper EP",
    artist: "Emmanuel",
    type: "12\" Vinyl",
    price: "Sold Out",
    soldOut: true,
    catalog: "MONNOM004",
    url: "https://monnomblack.bandcamp.com/album/vyper-ep",
    img: "https://f4.bcbits.com/img/a2668960584_10.jpg",
    desc: ""
  },
  {
    title: "Body Music LP",
    artist: "Thomas P. Heckmann",
    type: "Triple Vinyl LP",
    price: "Sold Out",
    soldOut: true,
    catalog: "MONNOM013",
    url: "https://monnomblack.bandcamp.com/album/body-music-lp",
    img: "https://f4.bcbits.com/img/a4218549728_10.jpg",
    desc: ""
  },
  {
    title: "Digi Spa EP",
    artist: "LDS",
    type: "12\" Vinyl",
    price: "Sold Out",
    soldOut: true,
    catalog: "MONNOM033",
    url: "https://monnomblack.bandcamp.com/album/digi-spa-ep",
    img: "https://f4.bcbits.com/img/a0937803696_10.jpg",
    desc: ""
  },
  {
    title: "Dead Eyes Society LP",
    artist: "Umwelt",
    type: "Double Vinyl LP",
    price: "Sold Out",
    soldOut: true,
    catalog: "MONNOM029",
    url: "https://monnomblack.bandcamp.com/album/dead-eyes-society-lp",
    img: "https://f4.bcbits.com/img/a3780987534_10.jpg",
    desc: ""
  },
  {
    title: "The World Of Monnom Black",
    artist: "Various Artists",
    type: "Triple 12\" Vinyl EP",
    price: "Sold Out",
    soldOut: true,
    catalog: "MONNOM017",
    url: "https://monnomblack.bandcamp.com/album/the-world-of-monnom-black",
    img: "https://f4.bcbits.com/img/a3152791254_10.jpg",
    desc: ""
  },
  {
    title: "Body Music Remixes",
    artist: "Thomas P. Heckmann",
    type: "Red & Black 12\" Vinyl",
    price: "Sold Out",
    soldOut: true,
    catalog: "MONNOM016",
    url: "https://monnomblack.bandcamp.com/album/body-music-remixes",
    img: "https://f4.bcbits.com/img/a0476765670_10.jpg",
    desc: ""
  }
];
